// <auto-generated />
namespace ElektronicznyKonsolowy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class userMessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userMessages));
        
        string IMigrationMetadata.Id
        {
            get { return "202411051319222_userMessages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
